---

# List of Debian packages installed by netlab.auth
auth_packages: [ 'libpam-cracklib','libpam-systemd' ]

# List of common system groups
auth_system_groups:
  -sftp-only

  # Allow user root to login
  auth_root_login: true

  # Allow techops_dba user to login
  auth_users_list: [ 'techops_dba' ]

  # Allow services to login
  auth_services_list: []

  # Enable password checking via cracklib
  auth_cracklib: true

